services:
  etc-redis:
    container_name: redis
    image: redis:7.4.3-alpine3.21
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "password"]
    networks:
      - todolist

  etc-postgres:
    container_name: pg-database
    image: postgres:17-alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todolist
    ports:
      - 5432:5432
    networks:
      - todolist

networks:
  todolist:

volumes:
  todolist:
# prod image test
# docker build -t nestjs-todolist:prod .
# docker run --rm --env-file .env.prod -p 3100:3000 --network todolist nestjs-todolist:prod
